spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: Abcd123@
    driver-class-name: com.mysql.cj.jdbc.Driver
batch:
  initialize-schema: never
 
  
    